//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// Donut.rc で使用
//
#define ID_GETFAVICONFROMFILE           3
#define ID_CREATE_FOLDER                3
#define ID_GETFAVICONFROMURL            4
#define IDD_ABOUTBOX                    100
#define IDD_FORM_TOOLBAR                101
#define ID_DONUTVIEW                    102
#define IDD_PROPPAGE_MDITAB             103
#define IDD_PROPPAGE_DLCONTROL          104
#define ID_SB_PANE0                     105
#define ID_LINKBAR_NONE                 106
#define IDD_PROPPAGE_ADDRESSBAR         107
#define ID_BACKUPOPTION_CHANGED         108
#define ID_VIEW_SETFOCUS                109
#define ID_VIEW_REFRESH_FAVBAR          110
#define ID_VIEW_SETFOCUS_INTERNAL       111
#define ID_VIEW_SAVEFOCUS_INTERNAL      112
#define ID_VIEW_SETFORCEFOCUS_INTERNAL  113
#define ID_DEBUG_CHECK_FOCUS            114
#define ID_FAVORITE_PLACEMENT           115
#define ID_VIEW_IDLE                    116
#define ID_VIEW_FONT_SIZE               117
#define ID_VIEW_ADDBAR_DROPDOWN         118
#define ID_FAVORITES_DROPDOWN           119
#define IDR_MAINFRAME                   120
#define IDR_MDICHILD                    121
#define ID_FAVORITES_GROUP_DROPDOWN     122
#define IDD_CLIPBAR_FORM                123
#define IDC_POINTER_CMD                 124
#define IDC_POINTER_END                 125
#define ID_CSS_DROPDOWN                 126
#define ID_PANEL_TYPE                   127
#define ID_PANEL_NAVI                   128
#define ID_SCRIPT                       129
#define IDR_GOBUTTON                    201
#define IDB_FAVBAR                      202
#define IDD_IGNORED_URLS                203
#define IDD_PROPPAGE_MAIN               204
#define IDB_FAVBAR_HOT                  205
#define IDD_PROPPAGE_EXPMENU            206
#define IDD_PROPPAGE_FAVORITEMENU       206
#define IDD_PROPPAGE_IGNOREDURLS        207
#define IDD_PROPPAGE_STARTUP            208
#define IDD_PROPPAGE_FILENEW            209
#define IDD_DIALOG_OPENURL              210
#define IDR_MENU_TAB                    211
#define IDD_PROPPAGE_CLOSETITLES        212
#define IDB_LINKBAR                     213
#define IDB_GOBUTTON                    214
#define IDB_GOBUTTON_HOT                215
#define IDB_MAINFRAME_TOOLBAR           216
#define IDB_MAINFRAME_TOOLBAR_HOT       217
#define IDB_MDITAB                      218
#define IDB_MAINFRAME_LARGE_TOOLBAR_HOT 219
#define IDB_MAINFRAME_LARGE_TOOLBAR     220
#define IDR_MENU_FAVTREE_BAR            221
#define IDD_DIALOG_RENAMEFILE           222
#define IDR_FILE_NEW                    223
#define IDD_PROPPAGE_EXECUTABLE         224
#define IDR_VIEW_FONT_SIZE              225
#define IDD_PROPPAGE_CONFIRMDLG         226
#define IDR_FILE_NEW_CLIPBOARD          227
#define IDD_PROPPAGE_PROXY              228
#define IDD_PROPPAGE_KEYBOARD           229
#define IDD_PROPPAGE_TOOLBAR            230
#define IDR_MULTIMEDIA                  231
#define IDR_SECURITY                    232
#define IDR_COOKIE                      233
#define IDR_TOOLBAR                     234
#define IDR_EXPLORERBAR                 235
#define IDR_MOVE                        236
#define IDR_OPTION                      238
#define IDR_AUTO_REFRESH                239
#define IDR_DOUBLE_CLOSE                240
#define IDR_COOKIE_IE6                  241
#define IDR_VIEW_FORWARD                242
#define IDR_VIEW_BACK                   243
#define IDB_SEARCHBUTTON_HOT            244
#define IDB_MAINFRAME_TOOLBAR_DIS       245
#define IDB_SEARCHBUTTON                246
#define IDD_PROPPAGE_MAIN2              247
#define IDD_PROPPAGE_MOUSE              248
#define IDD_PROPPAGE_SEARCHBAR          249
#define IDD_PROPPAGE_MENU               250
#define IDR_MOUSE_EX_SEL                253
#define IDD_DIALOG_CMD_SELECT           254
#define IDD_PROPPAGE_EXPLORERBAR        255
#define IDR_DONUTP                      257
#define IDB_SECURE                      258
#define IDR_API                         259
#define IDB_SEARCHBUTTON_DIS            260
#define IDR_PANEL_TYPE                  264
#define IDR_SCRIPT                      265
#define IDD_PROPPAGE_PLUGIN             267
#define IDD_PROPPAGE_DETERRENT          268
#define IDR_SPECIAL                     269
#define IDR_DROPDOWN_FAV                270
#define IDR_DROPDOWN_FAVGROUP           271
#define IDR_DROPDOWN_SCRIPT             273
#define IDD_DIALOG_THUMBNAIL            274
#define IDD_PROPSHEET                   275
#define IDD_PROPPAGE_LINKBAR            276
#define IDR_SEARCHENGINE_MENU           277
#define IDR_TRAYICON_MENU               278
#define IDR_ZOOM_MENU                   279
#define IDR_RECENT_DOC                  280
#define IDB_EXPBAR                      281
#define IDR_THUMBNAIL_MENU              282
#define IDR_TEXT_WARNING                283
#define IDD_PROPPAGE_URLSECURITY        287
#define IDD_PROPPAGE_DESTROY            288
#define IDD_PROPPAGE_SKIN               289
#define IDD_PROPPAGE_MOUSEGESTURE       290
#define IDD_DIALOG_SEARCHHISTORY        291
#define IDR_HISTORY                     292
#define IDD_DIALOG_EXPROPERTY2          296
#define IDD_DIALOG_EXPROPERTY           297
#define IDD_DIALOG_CONTEXTMENU          300
#define IDD_DIALOG_ALPHA                302
#define IDD_PROPPAGE_MENU_RIGHTCLICK    303
#define IDI_NAVIGATELOCK                304
#define IDD_ACCESSKEYEDIT               307
#define IDD_DEBUGWINDOW                 308
#define IDI_DLSTOP                      309
#define IDB_DLOK                        310
#define IDB_DLERROR                     311
#define IDB_DLOPTIONS                   312
#define IDB_DLHELP                      313
#define IDD_DLOPTION                    314
#define IDI_GENERIC_DOCUMENT            315
#define IDB_FIND                        316
#define IDB_DLTOOLBAR                   317
#define IDM_DOWNLOADINGLISTVIEW         318
#define IDD_LINKEDITDIALOG              319
#define IDD_DLLIST                      320
#define IDD_PROPPAGE_USERDEFINEDCSS     321
#define IDD_PROPPAGE_USERDEFINEDCSS1    322
#define IDD_PROPPAGE_USERDEFINEDJAVASCRIPT 322
#define IDD_SCRIPTDETAIL                323
#define IDI_FOLDER                      324
#define IDD_RENAMEDIALOG                325
#define IDM_LINKBAR                     326
#define IDD_FAVORITE_EDIT               328
#define IDD_DIALOG1                     329
#define IDD_PROCESS_MONITOR             329
#define IDD_LOGININFOEDITOR             330
#define IDC_SLIDER                      1000
#define IDC_IGNORED_URL_LIST            1000
#define IDC_EDIT                        1001
#define IDC_EDIT_CB_EXT                 1001
#define IDC_LIST_URL                    1001
#define IDC_COMBO_STDTB_TEXT            1002
#define IDC_DEL_BUTTON                  1003
#define IDC_COMBO_STDTB_ICON            1004
#define IDC_BTN_DEL_URL                 1004
#define IDC_DEL_BUTTON2                 1004
#define IDC_STATIC_CB_EXT               1005
#define IDC_CHECK_CB_DIRECT             1006
#define IDC_DELALL_BUTTON               1007
#define IDC_URL_EDIT                    1008
#define IDC_LIST_CB_CONT                1009
#define IDC_ADD_BUTTON                  1010
#define IDC_BUTTON_OPEN                 1011
#define IDC_BTN_ADD_URL                 1011
#define IDC_CHECK_CB_FLUSH              1012
#define IDC_BTN_DELALL_URL              1012
#define IDC_BUTTON_DELETE               1013
#define IDC_CHECK_MDITAB_LEFT           1014
#define IDC_BUTTON_DELETEALL            1015
#define IDC_EDIT_TABTEXTMAX             1016
#define IDC_CHECK_CB_ON                 1017
#define IDC_CHECK_DLCTL_BGSOUNDS        1018
#define IDC_CHECK_DLCTL_VIDEOS          1019
#define IDC_CHECK_MDITAB_RIGHTCLICKCLOSE 1020
#define IDC_CHECK_DLCTL_DLACTIVEXCTLS   1021
#define IDC_CHECK_DLACTIVEXCTLS         1021
#define IDC_CHECK_DLCTL_RUNACTIVEXCTLS  1022
#define IDC_CHECK_RUNACTIVEXCTLS        1022
#define IDC_CHECK_DLCTL_SCRIPTS         1023
#define IDC_CHECK_SCRIPTS               1023
#define IDC_CHECK_DLCTL_JAVA            1024
#define IDC_CHECK_JAVA                  1024
#define IDC_CHECK_DLCTL_DLIMAGES        1025
#define IDC_CHECK_MAIN_NOACTIVATE       1026
#define IDC_CHECK_MAIN_NEWWINDOW        1027
#define IDC_CHECK_MAIN_NOINITWND        1028
#define IDC_CHECK_ONEINSTANCE           1029
#define IDC_CHECK_EXPMENU_ADDITIONAL    1030
#define IDC_EDIT_EXPMENU_ITEMTEXTMAX    1031
#define IDC_IGNORED_URL_VALID           1032
#define IDC_EDIT_EXPMENU_BREAKCOUNTMAX  1033
#define IDC_CHK_URL                     1033
#define IDC_CHECK_MAIN_LIMIT            1034
#define IDC_EDIT_MAIN_LIMITEDCOUNT      1035
#define IDC_RADIO_GOHOME                1036
#define IDC_RADIO_LATEST                1037
#define IDC_RADIO_DFG                   1038
#define IDC_EDIT_DFG                    1039
#define IDC_BUTTON_EXPDFG               1040
#define IDC_CHECK_MAIN_NOCLOSEDFG       1041
#define IDC_RADIO_BLANK                 1042
#define IDC_RADIO_COPY                  1043
#define IDC_RADIO_HOME                  1044
#define IDC_RADIO_NOINITWIN             1045
#define IDC_BUTTON_REF                  1046
#define IDC_EDIT_URL                    1047
#define IDC_CHECK_MAIN_NOMDI            1048
#define IDC_CHECK_MAIN_VIEWCLIPBOARD    1049
#define IDC_CHECK_MDITAB_MULTILINE      1050
#define IDC_CHECK_SCROLLBAR             1051
#define IDC_CHECK_MAIN_BACKUP           1052
#define IDC_EDIT_MAIN_BACKUPTIME        1053
#define IDC_CHECK_MAIN_DEFAULT          1054
#define IDC_EDIT_MAIN_AUTOREFRESHTIME_MIN 1055
#define IDC_CHECK_STARTUP_ACTIVATE      1056
#define IDC_EDIT_MAIN_AUTOREFRESHTIME_SEC 1057
#define IDC_CHECK_MAIN_NOACTIVATE_NEWWIN 1058
#define IDC_CHECK_NEWWIN                1059
#define IDC_CHECK_ABR_NEWWIN            1060
#define IDC_CHECK_AUTOCOMPLETE          1061
#define IDC_CHECK_ABR_AUTOCOMPLETE      1062
#define IDC_CHECK_MDITAB_DOUBLECLICKCLOSE 1063
#define IDC_CHECK_ADB_NOACTIVATE        1064
#define IDC_CHECK_MAIN_ADDFAVORITEOLDSHELL 1065
#define IDC_CHECK_MAIN_ORGFAVORITEOLDSHELL 1066
#define IDC_CHECK_EXPMENU_ADDITIONAL2   1067
#define IDC_RADIO_EXSEARCH_SJIS         1068
#define IDC_CHECK_ABR_TEXTVISIBLE       1069
#define IDC_RADIO_MDITAB_RIGHTCLICK     1070
#define IDC_CHECK_EXP_DRAGDROP          1071
#define IDC_RADIO_MDITAB_DOUBLECLICK    1072
#define IDC_RADIO_EXSEARCH_EUC          1073
#define IDC_RADIO_EXSEARCH_UTF8         1074
#define IDC_RADIO_MDITAB_XCLICK         1075
#define IDC_RADIO_ONCLOSE               1076
#define IDC_CHK_MSG_FILTER              1078
#define IDC_RADIO_ADD                   1079
#define IDC_CHK_BLOCK_MAILTO            1080
#define IDC_CHECK_MAIN_MAKECASH         1081
#define IDC_CHKBTN_TXT                  1082
#define IDC_CHECK_WHEEL                 1083
#define IDC_CHECK_MDITAB_FIXEDSIZE      1084
#define IDC_EDIT_MDITAB_FIXEDSIZEX      1085
#define IDC_EDIT_MDITAB_FIXEDSIZEY      1086
#define IDC_CHECK_NAVILOCK              1087
#define IDC_COMBO_MDITAB_ADDPOS         1088
#define IDC_COMBO_MDITAB_RIGHTCLICK     1089
#define IDC_COMBO_MDITAB_DOUBLECLICK    1090
#define IDC_COMBO_MDITAB_MCLICK         1091
#define IDC_COMBO_ONCLOSE               1092
#define IDC_CHECK_ABR_LOADTYPEDURLS     1093
#define IDC_CHECK_ABR_GOBTNVISIBLE      1094
#define IDC_CHECK_FAVMENU_ORDER         1095
#define IDC_CHECK_DRAW_ICON             1096
#define IDC_CHECK_FAVMENU_USER          1097
#define IDC_EDIT_FAVMENU_USER           1098
#define IDC_BUTTON_FAVMENU_USER         1099
#define IDC_EDIT_RENAMEFILE             1100
#define IDC_CHECK_EXP_HSCROLL           1101
#define IDC_BTN_TABSKIN_DIR             1102
#define IDC_BTN_BTNSKIN_DIR             1103
#define IDC_CHECK_SPACE_MIN             1103
#define IDC_CHECK_MAIN_LOADGLOBALOFFLINE 1104
#define IDC_CHECK_EXP_SPACE             1105
#define IDC_CHECK_MAIN_KILLDIALOG       1106
#define IDC_CHECK_EXP_ORGIMAGE          1107
#define IDC_BUTTON_CB_PASTE             1108
#define IDC_CHK_MOUSE_GESTURE           1108
#define IDC_CHECK_MDITAB_ANCHORCOLOR    1109
#define IDC_BUTTON_CB_PASTE_DONUT       1110
#define IDC_LIST_EXECUTABLE             1111
#define IDC_CHECK_STARTUP_WITH_PARAM    1112
#define IDC_CHECK_CFD_EXIT              1113
#define IDC_CHECK_CFD_CLOSEALL          1114
#define IDC_CHECK_MAIN_REGISTER_AS_BROWSER 1115
#define IDC_CHECK_CFD_CLOSEEXCEPT       1116
#define IDC_CHECK_MAIN_INHERIT_OPTIONS  1117
#define IDC_EDIT_USER_AGENT             1118
#define IDC_CHECK_MAIN_CSTM_MENU        1119
#define IDC_EDIT1                       1120
#define IDC_CHECK_MAIN_DEL_CASH         1121
#define IDC_EDIT3                       1121
#define IDC_EDIT_EXCLUDE                1121
#define IDC_VALUE1                      1121
#define IDC_RAND_CHK                    1122
#define IDC_VALUE2                      1122
#define IDC_CHECK_MAIN_DEL_COOKIE       1123
#define IDC_VALUE3                      1123
#define IDC_EDIT_RAND_MIN               1124
#define IDC_CHECK_MAIN_DEL_HISTORY      1125
#define IDC_BUTTON_BAR_FONT             1126
#define IDC_IE_CHK                      1127
#define IDC_EDIT_RAND_SEC               1128
#define IDC_EDIT_CTRL_ENTER             1129
#define IDC_EDIT2                       1130
#define IDC_CMB_CATEGORY                1131
#define IDC_NAME2                       1131
#define IDC_CMB_CATEGORY2               1132
#define IDC_NAME3                       1132
#define IDC_CMB_COMMAND                 1133
#define IDC_EDIT_SZ_PAIN2               1134
#define IDC_CMB_COMMAND2                1134
#define IDC_LOCAL_CHK                   1135
#define IDC_EDIT_NOW_KEY                1136
#define IDC_ED_TABSKIN_PATH             1137
#define IDC_EDIT_NEW_KEY                1138
#define IDC_BTN_DEL                     1139
#define IDC_BTN_SET                     1140
#define IDC_STC01                       1141
#define IDC_CHK_CMDUPDATE               1142
#define IDC_CHK_CMDMOVE                 1143
#define IDC_LIST_ICON                   1144
#define IDC_BTN03                       1145
#define IDC_BTN01                       1146
#define IDC_BTN02                       1147
#define IDC_BTN04                       1148
#define IDC_HOMEPAGE                    1149
#define IDC_HOMEPAGE_BMP                1150
#define IDC_CHECK_CTRL_ENTER            1151
#define IDC_BTN05                       1152
#define IDC_CHECK_SHIFT_ENTER           1153
#define IDC_EDIT_SZ_PAIN1               1154
#define IDC_CHK_MENU                    1155
#define IDC_CHK_TOOLBAR                 1156
#define IDC_CHK_LINK                    1157
#define IDC_CHK_TAB                     1158
#define IDC_CHK_SEARCH                  1159
#define IDC_CHK_ADRESS                  1160
#define IDC_CHK_STATUS                  1161
#define IDC_NO_CSTM_IE_MENU             1162
#define IDC_CHK_SWAP_PAIN               1163
#define IDC_CMB_RL                      1163
#define IDC_CMB_RM                      1164
#define IDC_CMB_RW_UP                   1165
#define IDC_CMB_RW_DOWN                 1166
#define IDC_CMB_LINK_M                  1167
#define IDC_CHECK_NOCLOSE_NAVILOCK      1168
#define IDC_LISTBOX1                    1169
#define IDC_BTN_CLEAR                   1174
#define IDC_BTN_ADD                     1177
#define IDC_LIST1                       1178
#define IDC_LIST_PROCESS                1178
#define IDC_LIST2                       1179
#define IDC_BTN_UP                      1180
#define IDC_NO_CSTM_TXT_MENU            1181
#define IDC_BTN_DOWN                    1182
#define IDC_CMB_TAR                     1183
#define IDC_BTN_LEFT                    1184
#define IDC_BTN_UP1                     1185
#define IDC_BTN_RIGHT                   1186
#define IDC_BTN_DOWN1                   1187
#define IDC_LISTBOX                     1188
#define IDC_BTN_UP2                     1189
#define IDC_BTN_ADD1                    1190
#define IDC_BTN_DEL1                    1191
#define IDC_BTN_ADD2                    1192
#define IDC_BTN_DEL2                    1193
#define IDC_BTN_DOWN2                   1194
#define IDC_SETBTN_SIDE1                1195
#define IDC_SETBTN_SIDE2                1196
#define IDC_BTN_ADD_TITLE               1196
#define IDC_SETBTN_RL                   1197
#define IDC_BTN_DELALL_TITLE            1197
#define IDC_SETBTN_RM                   1198
#define IDC_BTN_DEL_TITLE               1198
#define IDC_SETBTN_RW_UP                1199
#define IDC_EDIT_TITLE                  1199
#define IDC_SETBTN_RW_DOWN              1200
#define IDC_LIST_TITLE                  1200
#define IDC_SETBTN_RX1                  1201
#define IDC_CHK_TITLE                   1201
#define IDC_SETBTN_RX2                  1202
#define IDC_CHECK_ADDLINKACTIVERIGHT    1204
#define IDC_BTN_ADD3                    1205
#define IDC_BTN_DEL3                    1206
#define IDC_CHECK_HEIGHTCOUNT           1207
#define IDC_EDIT_HEIGHTCOUNT            1208
#define IDC_LIST_THUMBNAIL              1209
#define IDC_APPLY                       1210
#define IDC_TREEVIEW                    1211
#define IDC_CHECK_MAIN_OPTIONSTYLE      1212
#define IDC_CHECK_STARTUP_SAVE_FB       1213
#define IDC_CHECK_FILTER                1214
#define IDC_CHECK_REPLACE               1215
#define IDC_EDITINFO                    1216
#define IDC_STATIC_VERSION              1217
#define IDC_CHECK_R_EQUAL_L             1218
#define IDC_STATIC_FIRST                1219
#define IDC_STATIC_SECOND               1220
#define IDC_CHECK_MAIN_DEL_RECENTCLOSE  1223
#define IDC_LIST_SKIN                   1224
#define IDC_BUTTON_APPLY                1225
#define IDC_STATIC_DESC                 1226
#define IDC_STATIC_NAME                 1227
#define IDC_BTN_SEARCH                  1228
#define IDC_DATETIMEPICKER1             1229
#define IDC_DATETIMEPICKER2             1230
#define IDC_CHECK_DATE                  1231
#define IDC_EDIT_KEYWORD                1232
#define IDC_BTN_CANCEL                  1233
#define IDC_BUTTON_FOLDER               1235
#define IDC_EDIT_USER                   1236
#define IDC_CHECK_CFD_STOPSCRIPT        1237
#define IDC_CHECK_LASTSEL               1238
#define IDC_SEARCH_NOWORDBUTTON         1239
#define IDC_COMBO_DRAGDROP              1240
#define IDC_COMBO_CTRL_ENTER            1241
#define IDC_COMBO_SHIFT_ENTER           1242
#define IDC_STATIC_TITLE                1243
#define IDC_BUTTON_DEFAULT              1244
#define IDC_BUTTON_CONTEXTMENU          1246
#define IDC_CHECK_ENABLE                1247
#define IDC_CHECK_MOUSEDOWNSELECT       1248
#define IDC_TRAVELLOG_GROUP             1249
#define IDC_TRAVELLOG_CLOSE             1250
#define IDC_CHECK_ACTIVEWINDOW          1251
#define IDC_CHECK_MENUORDER             1252
#define IDC_CHECK_RESETORDER            1253
#define IDC_COMBO_MRU_MENUTYPE          1254
#define IDC_EDIT_MRUCOUNT               1255
#define IDC_STATIC_MRU_MINMAX           1256
#define IDC_CHECK_AUTOHILIGHT           1257
#define IDC_TOOLTIP                     1258
#define IDC_CHECK_EXP_AUTOSHOW          1259
#define IDC_STATIC_EXSEARCH_FRONTURL    1260
#define IDC_STATIC_EXSEARCH_BACKURL     1261
#define IDC_STATIC_EXSEARCH_ENCODE      1262
#define IDC_EDIT_EXSEARCH_FRONTURL      1263
#define IDC_EDIT_FRONTURL               1263
#define IDC_EDIT_FRONTURL2              1264
#define IDC_STATIC_EXSEARCH_FRONTKEYWORD 1265
#define IDC_RADIO_EXSEARCH_NONE         1266
#define IDC_STATIC_EXSEARCH             1267
#define IDC_STATIC_EXSEARCH_BACKKEYWORD 1268
#define IDC_EDIT_EXSEARCH_FRONTKEYWORD  1269
#define IDC_EDIT_EXSEARCH_BACKURL       1270
#define IDC_EDIT_EXSEARCH_BACKKEYWORD   1271
#define IDC_CHECK_EXSEARCH_ADDRESSBAR   1272
#define IDC_CHECK_ENG_CHG_GO            1274
#define IDC_CHECK_DROP_GO               1275
#define IDC_CHECK_SCROLLCENTER          1276
#define IDC_CHECK_HISTORY_SAVE          1277
#define IDC_ED_HISTORY_CNT              1278
#define IDC_CHECK_NO_REPOSITION         1279
#define IDC_CHECK_KEY_CHG_GO            1280
#define IDC_ED_AUTHOR_URL               1281
#define IDC_ED_AUTHOR_EMAIL             1282
#define IDC_ED_PLUGIN_VER               1283
#define IDC_ED_PLUGIN_DATE              1284
#define IDC_ED_PLUGIN_COMMENT           1285
#define IDC_ED_PLUGIN_NAME              1286
#define IDC_ED_AUTHOR_NAME              1287
#define IDC_BTN_SETTING                 1288
#define IDC_LIST_PLUGIN                 1289
#define IDC_ED_PLUGIN_KIND              1290
#define IDC_CHECK_NOBUTTON              1291
#define IDC_STC_SIDE1                   1292
#define IDC_STC_SIDE2                   1293
#define IDC_STC_RL                      1294
#define IDC_STC_RM                      1295
#define IDC_STC_RW_UP                   1296
#define IDC_STC_RW_DOWN                 1297
#define IDC_STC_RX1                     1298
#define IDC_STC_RX2                     1299
#define IDC_ADDRESS_BAR_ICON_EXE        1300
#define IDC_MENU_BAR_STYLE_JAPAN        1301
#define IDC_MENU_BAR_STYLE_1CH          1302
#define IDC_MENU_BAR_STYLE_ENGLISH      1303
#define IDC_LINKBAR_SMALLICON           1306
#define IDC_LINKBAR_LARGEICON           1307
#define IDC_LINKBAR_NOICON              1308
#define IDC_LINKBAR_EDIT_FOLDER         1309
#define IDC_LINKBAR_BUTTON_FOLDER       1310
#define IDC_SEARCH_PAGEBUTTON           1315
#define IDC_STATIC_TO_TRAY              1316
#define IDC_CHECK_CTRLTAB_MDI           1317
#define IDC_CHECK_CFD_CLOSELEFTRIGHT    1319
#define IDC_RADIO_NO2TRAY               1320
#define IDC_RADIO_MINBTN2TRAY           1321
#define IDC_RADIO_CLOSEBTN2TRAY         1322
#define IDC_EDIT_EXPROP_URL             1323
#define IDC_BTN_EXPROP_URL              1324
#define IDC_EDIT_NEWPAGE_USER           1325
#define IDC_RADIO_START_USER            1326
#define IDC_BTN_URLSEC_SETTING          1327
#define IDC_BTN_URLSEC_UP               1328
#define IDC_BTN_URLSEC_DOWN             1329
#define IDC_STATIC_AUTOUPDATE           1330
#define IDC_CHK_URLSEC_REGEX            1331
#define IDC_CHK_URLSEC_ACTPAG           1332
#define IDC_BTN_DFLTBASE                1333
#define IDC_CHK_TITLECLOSE              1334
#define IDC_CHK_URLSECURITY             1335
#define IDC_STATIC_IMG_AUTO_RESIZE      1336
#define IDC_RADIO_IMG_AUTO_RESIZE_NONE  1337
#define IDC_RADIO_IMG_AUTO_RESIZE_FIRST 1338
#define IDC_RADIO_IMG_AUTO_RESIZE_NORM  1339
#define IDC_BTN_NEWPAGE_USER            1340
#define IDC_BTN_ADDRESS_BAR_EXE         1341
#define IDC_CHK_USER_AGENT              1342
#define IDC_TREE1                       1343
#define IDC_TREE                        1343
#define IDC_CHECK_SAVE_SEARCHWORD       1344
#define IDC_CHECK_FIREFOXLIKE           1345
#define IDC_TABBAR_FONT                 1346
#define IDC_ADDRESSBAR_FONT             1347
#define IDC_LINKBAR_FONT                1348
#define IDC_SEARCHBAR_FONT              1349
#define IDC_PROXYCMB_FONT               1350
#define IDC_TABBAR_STATIC               1351
#define IDC_ADDRESSBAR_STATIC           1352
#define IDC_SEARCHBAR_STATIC            1353
#define IDC_LINKBAR_STATIC              1354
#define IDC_PROXYCMB_STATIC             1355
#define IDC_COMBO_MINIMUM_LENGTH        1356
#define IDC_CHECK_USE_SHORTCUT          1357
#define IDC_EDIT_TABSEPARATORWIDTH      1358
#define IDC_CHECK_SEARCHLIST_WIDTH      1359
#define IDC_EDIT_SEARCHLIST_WIDTH       1360
#define IDC_LIST_COMMAND                1361
#define IDC_LIST_MENU                   1362
#define IDC_BUTTON_ADD                  1363
#define IDC_BUTTON_REMOVE               1364
#define IDC_BUTTON_ADD_SEPARATOR        1365
#define IDC_CMB_TARGET                  1366
#define IDC_BUTTON_APPLYMENU            1367
#define IDC_BUTTON_RESET                1368
#define IDC_BUTTON_EXAMPLE              1369
#define IDC_EDIT_ACCESSKEY              1370
#define IDC_CHECK_RESTORE_OPTION        1372
#define IDC_CHECK1                      1373
#define IDC_CHECK_DRAW_FAVICON          1373
#define IDC_CHECK_EXTERNALNEWTAB        1373
#define IDC_CHECK_SHOWICONONLY          1373
#define IDC_CHECK_PACK_ITEM             1373
#define IDC_EDIT_DOWNLOADFOLDER         1374
#define IDC_BUTTON_FOLDERSELECT         1375
#define IDC_CHECK_OPENDIALOG_BEFOREDL   1376
#define IDC_CHECK_CLOSEAFTERALLDL       1377
#define IDC_CHK_DLMANAGER               1378
#define IDC_CHECK_RIGHT_DRAGDROP        1379
#define IDC_CHECK_USERECT               1380
#define IDC_COMBO_TSEARCH               1381
#define IDC_COMBO_LSEARCH               1382
#define IDC_COMBO_CSEARCH               1383
#define IDC_COMBO_RSEARCH               1384
#define IDC_COMBO_BSEARCH               1385
#define IDC_CHK_ONLYTHISURL             1386
#define IDC_CHK_IGNORE_BLANK            1387
#define IDC_CHECK_USEPOST               1388
#define IDC_CHK_FOCUSTOSEARCHBAR        1389
#define IDC_EDIT_IMGDOWNLOADFOLDER      1390
#define IDC_BUTTON_IMGFOLDERSELECT      1391
#define IDC_RADIO_OVERWRITEPROMPT       1392
#define IDC_RADIO_USEUNIQUENUMBER       1393
#define IDC_EDIT_SHORTCUTCODE           1394
#define IDC_EDIT_DEFAULT_USER_AGENT     1395
#define IDC_BTN_CHANGE_COMMAND          1396
#define IDC_SHOWFAVICON                 1397
#define IDC_CHECK_CENTERALIGN           1398
#define IDC_EDIT_OFFSETACTIVEX          1399
#define IDC_EDIT_OFFSETACTIVEY          1400
#define IDC_EDIT_OFFSETNORMALX          1401
#define IDC_EDIT_OFFSETNORMALY          1402
#define IDC_EDIT_OFFSETMSELECTX         1403
#define IDC_EDIT_OFFSETMSELECTY         1404
#define IDC_CHK_USECUSTOMFINDBAR        1405
#define IDC_RADIO_NONE                  1406
#define IDC_RADIO_CASH                  1407
#define IDC_RADIO_ALWAYS                1408
#define IDC_CMB_DOWNLOADFOLDER          1409
#define IDC_CMB_IMGDOWNLOADFOLDER       1410
#define IDC_DLSTART                     1411
#define IDC_DLFINISH                    1412
#define IDC_LIST_DL                     1413
#define IDC_GETDLFOLDER                 1414
#define IDC_COMBO_PARALLELDL            1415
#define IDC_COMBO_DLFOLDER              1416
#define IDC_CMB_DLLISTOPTION            1417
#define IDC_COMBO_CSS                   1419
#define IDC_BUTTON_CSSEDIT              1420
#define IDC_BUTTON_OPENCSSFOLDER        1421
#define IDC_BUTTON_CHANGEAPPLY          1424
#define IDC_BUTTON_OPENJSFOLDER         1425
#define IDC_BUTTON_JSEDIT               1426
#define IDC_COMBO_JS                    1427
#define IDC_CHECK2                      1428
#define IDC_CHECK_EXTERNALNEWTABACTIVE  1428
#define IDC_CHECK_NOSHOWDRAGIMAGE       1428
#define IDC_CHECKBOX1                   1428
#define IDC_STATIC_SCRIPTPOSITION       1429
#define IDC_CHECKBOX2                   1429
#define IDC_SYSLINK_HP                  1430
#define IDC_STATIC_DISCRIPTION          1431
#define IDC_STATIC_FILENAME             1432
#define IDC_BUTTON_RELOAD               1433
#define IDC_BUTTON_INSTALL              1434
#define IDC_EDIT_INCLUDE                1435
#define IDC_EDIT_NAME                   1436
#define IDC_SPIN_MAXTEXTWIDTH           1437
#define IDC_BTN_LINKIMPORTFROMFOLDER    1438
#define IDC_BTN_LINKEXPORTTOFOLDER      1439
#define IDC_EDIT_MAXTEXTWIDTH           1440
#define IDC_COMBO_BROWSREOPERATINGMODE  1441
#define IDC_BUTTON_MATCHTEST            1442
#define IDC_BUTTON_LINKIMPORTFORMFOLDER 1443
#define IDC_BUTTON_LINKEXPORTTOFOLDER   1444
#define ID_APPLY                        1444
#define IDC_STATIC_URL                  1445
#define ID_KILLPROCESS                  1446
#define IDC_URL_LIST                    1447
#define IDC_CHECKNAME1                  1448
#define IDC_CHECKNAME2                  1449
#define IDC_BTN_APPLY                   1450
#define IDC_BTN_DELETE                  1452
#define IDC_BTN_TEST                    1453
#define IDC_BTN_IMPORT                  1454
#define IDC_BTN_EXPORT                  1455
#define IDC_NAME1                       1456
#define IDC_CHECK_VIDEO                 2000
#define IDC_CHECK_SOUND                 2001
#define IDC_CHECK_IMAGE                 2002
#define IDC_RADIO_RELOAD_NONE           2004
#define IDC_RADIO_RELOAD_15SEC          2005
#define IDC_RADIO_RELOAD_30SEC          2006
#define IDC_RADIO_RELOAD_1MIN           2007
#define IDC_RADIO_RELOAD_2MIN           2008
#define IDC_RADIO_RELOAD_5MIN           2009
#define IDC_RADIO_RELOAD_USER           2010
#define IDM_FOLLOWLINKN                 2137
#define COMMAND_RANGE_START             32772
#define ID_VIEW_BACK                    32772
#define ID_VIEW_FORWARD                 32773
#define ID_VIEW_STOP                    32774
#define ID_VIEW_ADDRESSBAR              32776
#define ID_FAVORITE_ADD                 32778
#define ID_VIEW_TABBAR                  32779
#define ID_EDIT_IGNORE                  32782
#define ID_VIEW_HOME                    32784
#define ID_FILE_PROPERTIES              32786
#define ID_VIEW_OPTION                  32787
#define ID_VIEW_GOBUTTON                32797
#define ID_VIEW_GO                      32798
#define ID_VIEW_SOURCE                  32799
#define ID_SEARCH_WEB                   32800
#define ID_SEARCH_HILIGHT               32801
#define ID_SEARCH_PAGE                  32802
#define ID_FAVORITE_ORGANIZE            32803
#define ID_EDIT_IGNORED_URLS            32805
#define ID_VIEW_FONT_MEDIUM             32809
#define ID_VIEW_OPTION_DONUT            32813
#define ID_DLCTL_SCRIPTS                32822
#define ID_DLCTL_DLACTIVEXCTLS          32823
#define ID_DLCTL_JAVA                   32824
#define ID_DLCTL_BGSOUNDS               32825
#define ID_DLCTL_VIDEOS                 32826
#define ID_DLCTL_DLIMAGES               32827
#define ID_DLCTL_RUNACTIVEXCTLS         32828
#define ID_WINDOW_CLOSE_ALL             32832
#define ID_FAVORITE_REFRESH             32833
#define ID_FILE_WORKOFFLINE             32834
#define ID_VIEW_FONT_LARGEST            32836
#define ID_VIEW_FONT_LARGER             32837
#define ID_VIEW_FONT_SMALLER            32838
#define ID_VIEW_FONT_SMALLEST           32839
#define ID_WINDOW_CLOSE_EXCEPT          32851
#define ID_MAIN_EX_NOACTIVATE           32855
#define ID_MAIN_EX_NEWWINDOW            32856
#define ID_VIEW_TOOLBAR_CUST            32857
#define ID_MAIN_PASTE_ADDRESS           32858
#define ID_EDIT_PASTE_URL               32859
#define ID_WINDOW_RESTORE               32862
#define ID_WINDOW_MAXIMIZE              32863
#define ID_WINDOW_MINIMIZE              32864
#define ID_WINDOW_SIZE                  32865
#define ID_WINDOW_MOVE                  32866
#define ID_INSERTPOINT_FAVORITEMENU     32867
#define ID_MENUITEM32870                32870
#define ID_MENUITEM32871                32871
#define ID_MENUITEM32873                32873
#define ID_FILE_NEW_CLIPBOARD           32874
#define ID_FILE_NEW_BLANK               32875
#define ID_FILE_NEW_COPY                32876
#define ID_AUTOREFRESH_NONE             32877
#define ID_AUTOREFRESH_15SEC            32878
#define ID_AUTOREFRESH_30SEC            32879
#define ID_AUTOREFRESH_1MIN             32880
#define ID_AUTOREFRESH_2MIN             32881
#define ID_AUTOREFRESH_5MIN             32882
#define ID_FAVORITE_GROUP_SAVE          32883
#define ID_FAVORITE_GROUP_ORGANIZE      32884
#define ID_INSERTPOINT_GROUPMENU        32885
#define ID_INSERTPOINT_GROUPMENU2       32886
#define ID_DOCHOSTUI_OPENNEWWIN         32887
#define ID_VIEW_REFRESH_ALL             32889
#define ID_VIEW_STOP_ALL                32890
#define ID_FAVORITE_GROUP_ADD           32891
#define ID_FILE_HOME                    32892
#define ID_FILE_NEW_HOME                32893
#define ID_WINDOW_NEXT                  32894
#define ID_SETFOCUS_ADDRESSBAR          32916
#define ID_TAB_LEFT                     32919
#define ID_TAB_RIGHT                    32920
#define ID_MAIN_EX_VIEWCLIPBOARD        32924
#define ID_INSERTPOINT_CHILDFAVORITEMENU 32925
#define ID_VIEW_TABBAR_MULTI            32926
#define ID_VIEW_LINKBAR                 32933
#define ID_VIEW_REFRESH_LINKBAR         32935
#define ID_VIEW_FULLSCREEN              32936
#define ID_OPTION_CLOSEPOPUP            32938
#define ID_MAIN_EX_NOACTIVATE_NEWWIN    32940
#define ID_VIEW_FAVEXPBAR               32941
#define ID_EDIT_PASTE_URLALL            32942
#define ID_MENUITEM32945                32945
#define ID_FAVTREE_BAR_STANDARD         32946
#define ID_FAVTREE_BAR_USER             32947
#define ID_FAVTREE_BAR_MYCOMPUTER       32948
#define ID_FAVTREE_BAR_GROUP            32949
#define ID_VIEW_CLIPBOARDBAR            32950
#define ID_FAVTREE_BAR_SHELLEXECUTE     32951
#define ID_FAVTREE_BAR_LOADREMOTEICON   32952
#define ID_VIEW_EXPBAR_SETFOCUS         32953
#define ID_FILE_NEW_CLIPBOARD_EX        32954
#define ID_VIEW_BACK1                   32955
#define ID_VIEW_BACK2                   32956
#define ID_VIEW_BACK3                   32957
#define ID_VIEW_BACK4                   32958
#define ID_VIEW_BACK5                   32959
#define ID_VIEW_BACK6                   32960
#define ID_VIEW_BACK7                   32961
#define ID_VIEW_BACK8                   32962
#define ID_VIEW_BACK9                   32963
#define ID_VIEW_FORWARD1                32964
#define ID_VIEW_FORWARD2                32965
#define ID_VIEW_FORWARD3                32966
#define ID_VIEW_FORWARD4                32967
#define ID_VIEW_FORWARD5                32968
#define ID_VIEW_FORWARD6                32969
#define ID_VIEW_FORWARD7                32970
#define ID_VIEW_FORWARD8                32971
#define ID_VIEW_FORWARD9                32972
#define ID_FILE_PRINTPREVIEW            32973
#define ID_FAVTREE_BAR_SINGLEEXPAND     32974
#define ID_EDIT_FIND_MAX                32975
#define ID_FILE_NEW_CLIPBOARD2          32976
#define ID_REGISTER_AS_BROWSER          32977
#define ID_EDIT_OPEN_SELECTED_REF       32978
#define ID_URLACTION_COOKIES            32979
#define ID_URLACTION_COOKIES_SESSION    32980
#define ID_TITLE_COPY                   32981
#define ID_URL_COPY                     32982
#define ID_EDIT_OPEN_SELECTED_TEXT      32983
#define ID_RESIZED                      32984
#define ID_GET_OUT                      32985
#define ID_EDIT_CLOSE_TITLE             32986
#define ID_F10                          32987
#define ID_FILE_NEW_SELECTED            32988
#define ID_FAVTREE_BAR_HISTORY          32989
#define ID_AUTOREFRESH_USER             32990
#define ID_VIEW_FAVEXPBAR_HIST          32991
#define ID_VIEW_HISTEXPBAR              32992
#define ID_GO_ADDRESSBAR                32993
#define ID_FAVTREE_BAR_HISTORY_TIME     32994
#define ID_WINDOW_REFRESH_EXCEPT        32995
#define ID_VIEW_COMMANDBAR              32996
#define ID_MULTIMEDIA                   32997
#define ID_SECURITY                     32998
#define ID_COOKIE                       32999
#define ID_TOOLBAR                      33000
#define ID_EXPLORERBAR                  33001
#define ID_MOVE                         33002
#define ID_OPTION                       33003
#define ID_AUTO_REFRESH                 33004
#define ID_POPUP_CLOSE                  33005
#define ID_TITLE_CLOSE                  33006
#define ID_DOUBLE_CLOSE                 33007
#define ID_DLCTL_CHG_MULTI              33008
#define ID_DLCTL_CHG_SECU               33009
#define ID_URLACTION_COOKIES_CHG        33010
#define ID_VIEW_UP                      33011
#define ID_VIEW_FAVEXPBAR_GROUP         33012
#define ID_VIEW_SEARCHBAR               33013
#define ID_FILE_OPEN_DEF                33014
#define ID_VIEW_SOURCE_SELECTED         33016
#define ID_VIEW_FAVEXPBAR_USER          33017
#define ID_URLACTION_COOKIES_HI         33018
#define ID_URLACTION_COOKIES_BLOCK      33019
#define ID_URLACTION_COOKIES_MIDHI      33020
#define ID_URLACTION_COOKIES_MID        33021
#define ID_URLACTION_COOKIES_LOW        33022
#define ID_URLACTION_COOKIES_ALL        33023
#define ID_URLACTION_COOKIES_CSTM       33024
#define ID_COOKIE_IE6                   33025
#define ID_SETFOCUS_SEARCHBAR           33026
#define ID_IE_EX_TAB                    33027
#define ID_APP_HELP                     33028
#define ID_OPEN_EXE_DIR                 33029
#define ID_STATUS_FILLTER               33030
#define ID_MESSAGE_FILTER               33031
#define ID_LEFT_CLOSE                   33032
#define ID_RIGHT_CLOSE                  33033
#define ID_SEARCHBAR_HILIGHT            33034
#define ID_SEARCHBAR_SEL_DOWN           33035
#define ID_EXPLORERBAR_AUTOSHOW         33036
#define ID_DLCTL_ON_OFF_MULTI           33037
#define ID_DLCTL_ON_OFF_SECU            33038
#define ID_MOUSE_GESTURE                33039
#define ID_STYLESHEET_BASE              33040
#define ID_STYLESHEET_OFF               33041
#define ID_BLOCK_MAILTO                 33045
#define ID_SEARCHBAR_SEL_UP             33046
#define ID_VIEW_FAVEXPBAR_SCRIPT        33047
#define ID_FAVTREE_BAR_SCRIPT           33048
#define ID_VIEW_FAVEXPBAR_PANEL         33053
#define ID_VIEW_PANELBAR                33054
#define ID_PRIVACYREPORT                33055
#define ID_SECURITYREPORT               33056
#define ID_VIEW_TOOLBAR_LOCK            33059
#define ID_SPECIAL_HOME                 33060
#define ID_SPECIAL_END                  33061
#define ID_SPECIAL_PAGEUP               33062
#define ID_SPECIAL_PAGEDOWN             33063
#define ID_SETFOCUS_SEARCHBAR_ENGINE    33064
#define ID_VIEW_SEARCHBUTTON            33065
#define ID_WINDOW_THUMBNAIL             33068
#define ID_VIEW_ENCODECONTAINER         33069
#define ID_SPECIAL_REFRESH_SEARCHENGIN  33073
#define ID_RECENT_DOCUMENT              33074
#define ID_STYLESHEET_USE_USERS         33076
#define ID_STYLESHEET_SET_USERS         33077
#define ID_SPECIAL_UP                   33078
#define ID_SPECIAL_DOWN                 33079
#define ID_VIEW_EXPLORERBAR_TAB         33080
#define ID_SEARCH_HISTORY               33081
#define ID_SELECT_USERFOLDER            33082
#define ID_VIEW_HISTORY_DAY             33083
#define ID_VIEW_HISTORY_RECENT          33084
#define ID_VIEW_HISTORY_SORT            33085
#define ID_VIEW_PLUGINBAR               33086
#define ID_PLUGIN_PLACEMENT             33087
#define ID_PLUGIN_MENU                  33088
#define ID_SEARCH_DIRECT                33089
#define ID_OPENLINK_DIRECT              33090
#define ID_COPY_TITLEANDURL             33091
#define ID_SAVE_FAVORITE_TO             33092
#define ID_AUTO_DIRECT                  33093
#define ID_TABLIST_DEFAULT              33094
#define ID_TABLIST_VISIBLE              33095
#define ID_TABLIST_ALPHABET             33096
#define ID_MAINFRAME_MINIMIZE           33097
#define ID_MAINFRAME_MAXIMIZE           33098
#define ID_SHOW_EXMENU                  33099
#define ID_JUMP_WEBSITE                 33100
#define ID_RECENDDOCUMENT_FIRST         33101
#define ID_SHOW_ACTIVEMENU              33102
#define ID_MAINFRAME_NORM_MAX_SIZE      33103
#define ID_SEARCHENGINE_MENU            33114
#define ID_FAVTREE_BAR_CLIPBOARD        33115
#define ID_FAVTREE_BAR_PANEL            33116
#define ID_FAVTREE_BAR_PLUGIN           33117
#define ID_VIEW_FAVEXPBAR_CLIPBOARD     33118
#define ID_VIEW_FAVEXPBAR_PLUGIN        33119
#define ID_VIEWPLUGINBAR                33120
#define ID_TAB_IDX_1                    33121
#define ID_TAB_IDX_2                    33122
#define ID_TAB_IDX_3                    33123
#define ID_TAB_IDX_4                    33124
#define ID_TAB_IDX_5                    33125
#define ID_TAB_IDX_6                    33126
#define ID_TAB_IDX_7                    33127
#define ID_TAB_IDX_8                    33128
#define ID_TAB_IDX_LAST                 33129
#define ID_HTMLZOOM_MENU                33130
#define ID_HTMLZOOM_ADD                 33131
#define ID_HTMLZOOM_SUB                 33132
#define ID_HTMLZOOM_400                 33133
#define ID_HTMLZOOM_200                 33134
#define ID_HTMLZOOM_150                 33135
#define ID_HTMLZOOM_125                 33136
#define ID_HTMLZOOM_100                 33137
#define ID_HTMLZOOM_075                 33138
#define ID_HTMLZOOM_050                 33139
#define ID_HTMLZOOM_100TOGLE            33140
#define ID_SEARCHBAR_WORD00             33150
#define ID_SEARCHBAR_WORD01             33151
#define ID_SEARCHBAR_WORD02             33152
#define ID_SEARCHBAR_WORD03             33153
#define ID_SEARCHBAR_WORD04             33154
#define ID_SEARCHBAR_WORD05             33155
#define ID_SEARCHBAR_WORD06             33156
#define ID_SEARCHBAR_WORD07             33157
#define ID_SEARCHBAR_WORD08             33158
#define ID_SEARCHBAR_WORD09             33159
#define ID_SEARCHBAR_WORD10             33160
#define ID_SEARCHBAR_WORD11             33161
#define ID_SEARCHBAR_WORD12             33162
#define ID_SEARCHBAR_WORD13             33163
#define ID_SEARCHBAR_WORD14             33164
#define ID_SEARCHBAR_WORD15             33165
#define ID_SEARCHBAR_WORD16             33166
#define ID_SEARCHBAR_WORD17             33167
#define ID_SEARCHBAR_WORD18             33168
#define ID_SEARCHBAR_WORD19             33169
#define ID_33170                        33170
#define ID_DEBUGCOMMAND                 33171
#define ID_33172                        33172
#define ID_FILE_OPEN_TABLIST            33173
#define ID_P_33174                      33174
#define ID_TAB_CLONE                    33175
#define ID_P_33176                      33176
#define ID_P_33177                      33177
#define ID_DLOPENOPTION                 33178
#define ID_DLAPP_ABOUT                  33179
#define ID_SHOW_DLMANAGER               33180
#define IDC_CHECK_SHOWWINDOW_ONDL       33181
#define ID_BINGTRANSLATE                33182
#define ID_BINGTRANSLATOR_MENU          33183
#define ID_COPYTRANSLATERESULT          33184
#define ID_A_DICTIONARY                 33185
#define ID_SAVEIMAGE                    33186
#define ID_FIND_PAGEUP                  33187
#define ID_FIND_PAGEDOWN                33188
#define ID_FIND_HIGHLIGHT               33189
#define ID_FIND_OPTION                  33190
#define ID_SET_DLFOLDER                 33191
#define ID_OPEN_DLFOLDER                33192
#define ID_RENAME_DLITEM                33193
#define ID_OPEN_SAVEFOLDER              33194
#define ID_OPEN_REFERER                 33195
#define ID_DUMMY_33196                  33196
#define ID_DUMMY_33197                  33197
#define ID_DUMMY_33198                  33198
#define ID_DUMMY_33199                  33199
#define ID_DUMMY_33200                  33200
#define ID_DUMMY_33201                  33201
#define ID_33202                        33202
#define ID_33203                        33203
#define ID_33204                        33204
#define ID_33205                        33205
#define ID_33206                        33206
#define ID_OPENLINK                     33207
#define ID_OPENNEWTABLINK               33208
#define ID_OPENLINKONNEWTAB             33209
#define ID_EDITLINK                     33210
#define ID_EDITLINKITEM                 33211
#define ID_DELETELINKITEM               33212
#define ID_ADDLINK                      33213
#define ID_ADDFOLDER                    33214
#define ID_ALLOPENLINKONFOLDER          33215
#define ID_ALLOPENLINKINFOLDER          33216
#define ID_OPENALLLINKINFOLDER          33217
#define ID_EDITFOLDERNAME               33218
#define ID_DELETE                       33219
#define ID_33220                        33220
#define ID_EDITEXPROPERTY               33221
#define ID_Menu                         33222
#define ID_ITEMNONE_33223               33223
#define ID_SORTBYNAME                   33224
#define ID_ID_SORTBYNAME                33225
#define ID_33226                        33226
#define ID_VIEW_ROOT                    33227
#define ID_Menu33228                    33228
#define ID_UNDOMENUITEM                 33229
#define ID_VIEW_PROCESSMONITOR          33230
#define ID_33231                        33231
#define ID_AUTOLOGIN                    33232
#define ID_AUTOLOGINEDIT                33233
#define ID_PLUGIN_COMMAND               33333
#define COMMAND_RANGE_END               34000
#define ID_INSERTPOINT_CSSMENU          35000
#define ID_INSERTPOINT_CSSMENU_END      35099
#define ID_INSERTPOINT_PANELTYPEMENU    35100
#define ID_INSERTPOINT_PANELTYPEMENU_END 35199
#define ID_INSERTPOINT_SCRIPTMENU       35200
#define ID_INSERTPOINT_SCRIPTMENU_END   36299
#define ID_INSERTPOINT_SEARCHENGINE     36300
#define ID_INSERTPOINT_SEARCHENGINE_END 37399
#define ENCODE_MENU_ID_MIN              48896
#define ENCODE_MENU_ID_MAX              49151
#define FAVORITE_MENU_ID_MIN            49152
#define FAVORITE_MENU_ID_MAX            53247
#define FAVGROUP_MENU_ID_MIN            53248
#define FAVGROUP_MENU_ID_MAX            55295
#define EXMENU_FIRST                    55300
#define EXMENU_USERDEFINE_MIN           55300
#define EXMENU_USERDEFINE_MAX           55499
#define EXMENU_LAST                     55499
#define ID_RECENTDOCUMENT_FIRST         56000
#define ID_RECENTDOCUMENT_1             56000
#define ID_RECENTDOCUMENT_2             56001
#define ID_RECENTDOCUMENT_3             56002
#define ID_RECENTDOCUMENT_4             56003
#define ID_RECENTDOCUMENT_5             56004
#define ID_RECENTDOCUMENT_6             56005
#define ID_RECENTDOCUMENT_7             56006
#define ID_RECENTDOCUMENT_8             56007
#define ID_RECENTDOCUMENT_9             56008
#define ID_RECENTDOCUMENT_LAST          56099
#define ID_DOCKINGPLUGIN_FIRST          56200
#define ID_DOCKINGPLUGIN_LAST           56250
#define ID_PROGRESS_PANE                61403
#define ID_COMBOBOX_PANE                61404
#define ID_SECURE_PANE                  61405
#define ID_PRIVACY_PANE                 61406
#define IDS_STRING61407                 61407

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        331
#define _APS_NEXT_COMMAND_VALUE         33234
#define _APS_NEXT_CONTROL_VALUE         1457
#define _APS_NEXT_SYMED_VALUE           130
#endif
#endif
